[context.deploy-preview]
environment = {STRIPE_PUBLISHABLE_KEY = "pk_test_51JJ3vNLOlCyqSHKr5xPVUVHcaD9WBEkIsxic1lK4e9LNkfyYnZ3iYLwINAXw78bZfl3kqCY47EraOGPYbqtDxFeI00jgjkf0Kp", STRIPE_SECRET_KEY = "sk_test_51JJ3vNLOlCyqSHKrp2vu93c9YzrXxDq7otphDYZqQTE10eZ0GsiVPJPxEOYOHEIBsMW9qjvtIZGPM2pcJTaYulvE00MlBr7pi9"}

[context.branch-deploy]
environment = {STRIPE_PUBLISHABLE_KEY = "pk_test_51JJ3vNLOlCyqSHKr5xPVUVHcaD9WBEkIsxic1lK4e9LNkfyYnZ3iYLwINAXw78bZfl3kqCY47EraOGPYbqtDxFeI00jgjkf0Kp", STRIPE_SECRET_KEY = "sk_test_51JJ3vNLOlCyqSHKrp2vu93c9YzrXxDq7otphDYZqQTE10eZ0GsiVPJPxEOYOHEIBsMW9qjvtIZGPM2pcJTaYulvE00MlBr7pi9"}

