name: Format
on:
  pull_request:
  push:
    branches: [main]
jobs:
  format:
    # Check if the PR is not from a fork
    # if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: yarn install
      - run: yarn format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.event.pull_request.head.ref }}
